### ISSUE TITLE
Model infeasible, but all constraints appear valid.

### ISSUE THREAD

**Issue by NatalieThurlby** [coin-or/pulp#254] opened 2019-12-19 15:58 UTC
Hi, first of all, I'm really enjoying using PuLP and finding it very useful, so thank you!

I'm looking to check which of my constraints are not being met by the returned solution to an infeasible problem (as a clue to which constraints I should relax).

I specify my model (called `model`) and constraints and then run the following:
```
solution_type = model.solve()

if solution_type == -1:
    warnings.warn('Problem infeasible.')
    for c_name in model.constraints:
        if not model.constraints[c_name].valid():
            print(c_name)
```
I get the 'Problem infeasible' warning, but none of my model constraints appears to be invalid, even ones that I can see are not satisfied by the current solution.

I'm wondering if I've misunderstood what .valid() is doing. Is there some other way of doing what I'm trying to do?

I'm using the pulp python package, version 1.6.10.

Thanks for your help!

**Comment by pchtsp** [comment] 2019-12-20 20:40
Hello there!

Thanks for reporting. Do you have a reproducible example we can use?
Are the bounds of your variables being respected?

-Franco

**Comment by pchtsp** [comment] 2020-07-04 22:49
I'll close this because there was no repsonse.

**Closed by pchtsp** 2020-07-04 22:49 UTC
