### ISSUE TITLE
Speeding up LpVariable.dicts

### ISSUE THREAD

**Issue by hovinh** [coin-or/pulp#154] opened 2017-10-24 09:38 UTC
Hi,

Currently, I'm working with approximately 1 million variable, and it took than half a day to read the input to the solver. At first, I thought it was the way I create ``indexs`` parameter (1-dimension list) that slow down the program, then I attempted to optimize. The best solution, which is praised by the community, is list comprehension syntax .

I took a look at the code itself as well, and I think we could refactor with this list comprehension syntax. What do you think?

**Comment by stumitchell** [comment] 2017-10-24 20:47
Which part of the code are you talking about?

**Comment by hovinh** [comment] 2017-10-25 01:48
I am talking about ``pulp.py`` >> class ``class LpVariable`` >> method ``dicts``.
You use the for loop to create the dictionary ``dicts``, meanwhile I suggest using list comprehension instead.

**Comment by pchtsp** [comment] 2019-09-30 19:46
sorry to respond this late.
1. Have you done performance tests to check if this is indeed faster?
2. Could you provide a pull request?

**Comment by manisharora** [comment] 2020-03-29 12:36
This issue needs to be corrected, its really slow

**Comment by pchtsp** [comment] 2020-04-05 22:49
@manisharora 
Do you have a reproducible example we can test? I usually create hundreds of thousands of variables in less than a second.

If not, I will have to close the issue.

thanks!

**Comment by manisharora** [comment] 2020-04-06 18:17
`#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr  4 23:39:14 2020

@author: digiplex
"""

import pulp
from pulp import lpDot
import numpy as np
import time

cons=np.arange(1,1001,1)
consarray=np.full((10,1000),cons)

model = pulp.LpProblem("option optimizer", pulp.LpMaximize)
var = list(pulp.LpVariable.dicts("f",np.arange(0,1000,1),upBound=10,lowBound = 0,cat="INTEGER").values())

t=time.time()
npdot_result=np.dot(consarray,var)
t1=time.time()
print("time for np.dot",t1-t)


t=time.time()
lpdot_result=lpDot(consarray,var)
t1=time.time()
print("time for lpDot",t1-t)

#lpDot Results are wrong`

**Comment by pchtsp** [comment] 2020-05-22 09:56
closing because no example provided.

**Closed by pchtsp** 2020-05-22 09:56 UTC
