### ISSUE TITLE
decision variable contain continuous when pulp solve 0-1 programming models 

### ISSUE THREAD

**Issue by Herema-Xu** [coin-or/pulp#283] opened 2020-04-08 03:40 UTC
Situation:

I am building 0-1 programming models , defined decision variable as an Binary, such as:
     x = pulp.LpVariable("_", [i for i in flights], [j for j in gates], lowBound=0, upBound=1, cat=LpBinary)

set pulp.fracGap=0.002, pulp.maxSeconds=20, and use prob.solve(PULP_CBC_CMD()) solving models。In the end, Made some cases verification models , we find one of this cases  had some problem， an exotic phenomenon appeared,  decision variable x[14,1] = 0.5 not 1.0, it  is not satisfied the define of decision variable. And in the Windows this phenomenon is disappeared. what's happend?

Software:
1) Python 3.6
2) Pulp 2.1

Hardware:
1）CentOS Linux release 7.4.1708 , x86_64

**Comment by pchtsp** [comment] 2020-05-04 09:39
Do you have an reproducible example we could run ourselves? if not, it's not going to be easy to help.

**Comment by amakarowsky** [comment] 2020-06-01 01:45
Hi @Herema-Xu - may I suggest saving an output .prt/.log file? I experienced a similar error (binary decision variable was set to 0.99999) with the XPRESS solver. Through inspecting .lp and .prt files we were able to determine that the integer gap was caused by XPRESS control parameters and not PULP itself.

**Comment by pchtsp** [comment] 2020-07-08 15:01
I'm closing the issue since there's no way to know without more information.

**Closed by pchtsp** 2020-07-08 15:01 UTC
