### ISSUE TITLE
Multithreading not working on Windows

### ISSUE THREAD

**Issue by multipitch** [coin-or/pulp#330] opened 2020-08-25 10:09 UTC
Details for the issue
--------------------

I've developed an optimization tool for a tank assignment problem. It works fine on Linux with both the latest version of CBC and with the pulp-bundled CBC, for either one or >1 threads (on a 6-core / 12-thread machine). When I run it on Windows, it works fine on one thread, but multithreading hangs when using the pulp version of CBC (I can't try "native" CBC as this is a work machine and installing it is proving difficult).
Since this is a very large MILP application, I've built a minimum example that exhibits the same behaviour.
The problem size needs to be sufficiently large so that it doesn't solve before it gets to the branch and bound phase.

```
import random

from pulp import LpProblem, LpMaximize, lpSum, LpVariable, LpBinary
from pulp.apis import PULP_CBC_CMD

PROBLEM_SIZE = 100000
THREADS = 4

prob = LpProblem("Knapsack problem", LpMaximize)
costs = [random.randint(1, 1000) for i in range(PROBLEM_SIZE)]
weights = [random.randint(1, 1000) for i in range(PROBLEM_SIZE)]
capacity = 1000 * 0.5 * 0.75 * PROBLEM_SIZE
x = LpVariable.dicts("x", range(PROBLEM_SIZE), cat=LpBinary)
prob += lpSum([costs[i] * x[i] for i in range(PROBLEM_SIZE)])
prob += lpSum([weights[i] * x[i] for i in range(PROBLEM_SIZE)]) <= capacity
prob.solve(solver=PULP_CBC_CMD(threads=THREADS))
```

#### What did you expect to see?

The problem above solving without crashing on Windows (solves fine on Linux)

#### What did you see instead?

If I change threads to 1, the above runs successfully.
If I have threads > 1, I get e.g....
```
PS C:\Users\user> python test.py
C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pulp\pulp.py:1195: UserWarning: Spaces are not permitted in the name. Converted to '_'
  warnings.warn("Spaces are not permitted in the name. Converted to '_'")
Welcome to the CBC MILP Solver
Version: 2.9.0
Build Date: Feb 12 2015

command line - C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\pulp\apis\..\solverdir\cbc\win\64\cbc.exe C:\Users\user\AppData\Local\Temp\141763b1d89749e09bdcafc1e35f0c78-pulp.mps max ratio None allow None threads 4 presolve on strong None gomory on knapsack on probing on branch printingOptions all solution C:\Users\user\AppData\Local\Temp\141763b1d89749e09bdcafc1e35f0c78-pulp.sol (default strategy 1)
At line 2 NAME          MODEL
At line 3 ROWS
At line 6 COLUMNS
At line 400007 RHS
At line 400009 BOUNDS
At line 500010 ENDATA
Problem MODEL has 1 rows, 100000 columns and 100000 elements
Coin0008I MODEL read with 0 errors
String of None is illegal for double parameter ratioGap value remains 0
String of None is illegal for double parameter allowableGap value remains 0
threads was changed from 0 to 4
String of None is illegal for integer parameter strongBranching value remains 5
Option for gomoryCuts changed from ifmove to on
Option for knapsackCuts changed from ifmove to on
Continuous objective value is 4.77437e+007 - 0.10 seconds
Cgl0004I processed model has 1 rows, 99636 columns (99636 integer (99276 of which binary)) and 99636 elements
Cutoff increment increased from 1e-005 to 0.9999
Cbc0038I Initial state - 1 integers unsatisfied sum - 0.0266022
Cbc0038I Solution found of -4.77437e+007
Cbc0038I Cleaned solution of -4.77437e+007
Cbc0038I Before mini branch and bound, 99635 integers at bound fixed and 0 continuous
Cbc0038I Full problem 1 rows 99636 columns, reduced to 0 rows 0 columns
Cbc0038I Mini branch and bound did not improve solution (1.13 seconds)
Cbc0038I Round again with cutoff of -4.77437e+007
Cbc0038I Reduced cost fixing fixed 98378 variables on major pass 2
Cbc0038I Pass   1: suminf.    0.00865 (1) obj. -4.77437e+007 iterations 2
Cbc0038I Solution found of -4.77437e+007
Cbc0038I Branch and bound needed to clear up 1 general integers
Cbc0038I Full problem 2 rows 99636 columns, reduced to 2 rows 6 columns
Cbc0038I Cleaned solution of -4.77437e+007
Cbc0038I Before mini branch and bound, 99634 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (1.54 seconds)
Cbc0038I Round again with cutoff of -4.77437e+007
Cbc0038I Reduced cost fixing fixed 99146 variables on major pass 3
Cbc0038I Pass   2: suminf.    0.02830 (1) obj. -4.77437e+007 iterations 0
Cbc0038I Solution found of -4.77437e+007
Cbc0038I Branch and bound needed to clear up 1 general integers
Cbc0038I Full problem 2 rows 99636 columns, reduced to 2 rows 5 columns
Cbc0038I Mini branch and bound could not fix general integers
Cbc0038I No solution found this major pass
Cbc0038I Before mini branch and bound, 99634 integers at bound fixed and 0 continuous
Cbc0038I Mini branch and bound did not improve solution (1.90 seconds)
Cbc0038I After 1.91 seconds - Feasibility pump exiting with objective of -4.77437e+007 - took 1.04 seconds
Cbc0012I Integer solution of -47743721 found by feasibility pump after 0 iterations and 0 nodes (1.93 seconds)
Cbc0013I At root node, 0 cuts changed objective from -47743725 to -47743725 in 1 passes
Cbc0014I Cut generator 0 (Probing) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.023 seconds - new frequency is 1
Cbc0014I Cut generator 1 (Gomory) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.002 seconds - new frequency is 1000
Cbc0014I Cut generator 2 (Knapsack) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.002 seconds - new frequency is 1000
Cbc0014I Cut generator 3 (Clique) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.001 seconds - new frequency is -100
Cbc0014I Cut generator 4 (MixedIntegerRounding2) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.008 seconds - new frequency is -100
Cbc0014I Cut generator 5 (FlowCover) - 0 row cuts average 0.0 elements, 0 column cuts (0 active)  in 0.013 seconds - new frequency is -100
Cbc0010I After 0 nodes, 1 on tree, -47743721 best solution, best possible -47743725 (3.53 seconds)
Cbc0012I Integer solution of -47743722 found by rounding after 1 iterations and 1 nodes (4.69 seconds)
Cbc0012I Integer solution of -47743722 found by heuristic after 0 iterations and 0 nodes (4.69 seconds)
```
...at the point above, execution hangs and I have to kill the program.

Useful extra information
-------------------------

#### What operating system are you using?

- [x] Windows: Windows 10
- [x] Linux: Arch
- [ ] Mac OS: ( _version:_ ___ )
- [ ] Other: ___

#### I'm using python version:

- [ ] 2.7
- [ ] 3.4
- [ ] 3.5
- [ ] 3.6
- [x] Other: 3.8.0

#### I installed PuLP via:

- [x] pypi (pip install pulp) - version 2.3 installed
- [ ] github
- [ ] Other: ___

**Comment by multipitch** [comment] 2020-08-25 10:26
Managed to get standalone CBC running on Windows (Cbc-master-x86_64-w64-mingw32.zip from [bintray](https://bintray.com/coin-or/download/Cbc/master)).
Multithreading works fine with this version of CBC too, so the problem seems to definitely be related to the version of CBC bundled with PuLP.

**Comment by tkralphs** [comment] 2020-08-26 17:27
This looks like a pure Cbc issue, not a PuLP issue. If you can attach the MPS file, we can transfer the issue over to Cbc. However, as the issue is with version 2.9, which is pretty old by now, I doubt we'll be able to give it much attention.

**Comment by multipitch** [comment] 2020-08-27 08:22
Agreed it looks to be a Cbc issue.
The issue doesn't seem to be present with the latest version of Cbc, which is working fine.

If you found what the root cause was in the version in PuLP, and backported a fix, the binaries in pulp would need to be replaced to implement this.
It would be easier to just package the latest binaries in pulp, as per #196

**Comment by pchtsp** [comment] 2020-08-31 10:20
If anyone makes a PR with the new version of the CBC binary for the three platforms, I promise to take a look. We wanted to deploy the binaries outside the pulp project but since that task has not yet been done we may as well keep updating the binaries.

**Comment by wanghao0911** [comment] 2020-09-08 07:03
I tested your demo on Linux and found that multi-threading does not speed up, or even slows down. May I ask your actual tank assignment project, under Linux, can multi-threading be accelerated?

**Comment by pchtsp** [comment] 2020-09-23 19:12
closing given that it's cbc related.

**Closed by pchtsp** 2020-09-23 19:12 UTC

**Comment by Silent-Fury** [comment] 2024-09-09 11:43
same here, 
python 3.12
pulp 2.9.0
cbc 2.10.3

**Comment by tkralphs** [comment] 2024-09-13 10:13
2.10.3 is quite an old release by now, but I doubt that anything will change by updating. Parallelizing solution of MILPs is not easy and there is no way to guarantee speed-up. Over an entire set of test instances, speedups should be expected on average (though not linear speedups in general), but on any given instance, it's possible to see a slowdown. This is just the nature of the beast.
