### ISSUE TITLE
An unexpected error occurred while tokenizing input

### ISSUE THREAD

**Issue by GoogleCodeExporter** [coin-or/pulp#46] opened 2015-03-15 03:22 UTC
```
What is the expected output? What do you see instead?
I expect to see the normal PuLP output, but I get an error instead that says

"ERROR: An unexpected error occurred while tokenizing input. The following 
traceback may be corrupted or invalid. The error message is: ('EOF in 
multi-line statement',(338,0))"

I have to do a ctrl+C keyboard interrupt in order to even see this, otherwise 
it would just run indefinitely.

What version of the product are you using? On what operating system?
I'm using the most recent version on Windows XP
```

Original issue reported on code.google.com by `kyle.w.a...@gmail.com` on 2 Jul 2012 at 11:08

**Comment by pchtsp** [comment] 2020-07-04 22:36
since this issue is really old, I'm going to close the issue. If you have a reproducible example, just create a new issue.

thanks.

**Closed by pchtsp** 2020-07-04 22:36 UTC
Labels: Priority-Medium, Type-Defect, auto-migrated
