### ISSUE TITLE
Resulting in an unoptimal solution on a simple problem

### ISSUE THREAD

**Issue by joaomanke** [coin-or/pulp#233] opened 2019-10-29 13:36 UTC
I have constructed a simple problem which resulted in the following lp file:

> \* Problem *\
> Minimize
> OBJ: 2594.0642408 x_0_0 + 474.183785953 x_0_1 + 1059.94022742 x_0_10
>  \+ 1380.71161204 x_0_11 + 1701.48299666 x_0_12 + 2022.25438127 x_0_13
>  \+ 1603.85692308 x_0_14 + 1924.62830769 x_0_15 + 2245.39969231 x_0_16
>  \+ 2566.17107692 x_0_17 + 2886.94246154 x_0_18 + 223.145311037 x_0_19
>  \+ 794.955170569 x_0_2 + 1450.44452174 x_0_3 + 2315.13260201 x_0_4
>  \+ 2635.90398662 x_0_5 + 195.252147157 x_0_6 + 516.023531773 x_0_7
>  \+ 836.794916388 x_0_8 + 739.168842809 x_0_9
> Subject To
> CA_0: x_0_0 + x_0_1 + x_0_10 + x_0_11 + x_0_12 + x_0_13 + x_0_14
>  \+ x_0_15 + x_0_16 + x_0_17 + x_0_18 + x_0_19 + x_0_2 + x_0_3 + x_0_4 + x_0_5
>  \+ x_0_6 + x_0_7 + x_0_8 + x_0_9 <= 23
> CD_0: 945 x_0_0 + 945 x_0_1 + 945 x_0_2 >= 21.8826931343
> CD_1: 945 x_0_0 + 945 x_0_10 + 945 x_0_11 + 945 x_0_12 + 945 x_0_13
>  \+ 3780 x_0_3 + 2835 x_0_4 + 2835 x_0_5 + 1890 x_0_6 + 1890 x_0_7 + 1890 x_0_8
>  \+ 945 x_0_9 >= 0
> CD_2: 945 x_0_1 + 2835 x_0_10 + 1890 x_0_11 + 945 x_0_12 + 4725 x_0_14
>  \+ 3780 x_0_15 + 2835 x_0_16 + 1890 x_0_17 + 945 x_0_18 + 945 x_0_4
>  \+ 1890 x_0_6 + 945 x_0_7 + 3780 x_0_9 >= 0
> CD_3: 945 x_0_1 + 945 x_0_10 + 1890 x_0_11 + 2835 x_0_12 + 3780 x_0_13
>  \+ 945 x_0_15 + 1890 x_0_16 + 2835 x_0_17 + 3780 x_0_18 + 5670 x_0_19
>  \+ 1890 x_0_2 + 945 x_0_5 + 945 x_0_6 + 1890 x_0_7 + 2835 x_0_8 >= 0
> CF_0: 945 x_0_0 + 945 x_0_1 + 945 x_0_2 <= 1018.30330976
> CF_1: 945 x_0_0 + 945 x_0_10 + 945 x_0_11 + 945 x_0_12 + 945 x_0_13
>  \+ 3780 x_0_3 + 2835 x_0_4 + 2835 x_0_5 + 1890 x_0_6 + 1890 x_0_7 + 1890 x_0_8
>  \+ 945 x_0_9 <= 945.018426602
> CF_2: 945 x_0_1 + 2835 x_0_10 + 1890 x_0_11 + 945 x_0_12 + 4725 x_0_14
>  \+ 3780 x_0_15 + 2835 x_0_16 + 1890 x_0_17 + 945 x_0_18 + 945 x_0_4
>  \+ 1890 x_0_6 + 945 x_0_7 + 3780 x_0_9 <= 1018.30309871
> CF_3: 945 x_0_1 + 945 x_0_10 + 1890 x_0_11 + 2835 x_0_12 + 3780 x_0_13
>  \+ 945 x_0_15 + 1890 x_0_16 + 2835 x_0_17 + 3780 x_0_18 + 5670 x_0_19
>  \+ 1890 x_0_2 + 945 x_0_5 + 945 x_0_6 + 1890 x_0_7 + 2835 x_0_8
>  <= 1018.30347044
> Bounds
> 0 <= x_0_0
> 0 <= x_0_1
> 0 <= x_0_10
> 0 <= x_0_11
> 0 <= x_0_12
> 0 <= x_0_13
> 0 <= x_0_14
> 0 <= x_0_15
> 0 <= x_0_16
> 0 <= x_0_17
> 0 <= x_0_18
> 0 <= x_0_19
> 0 <= x_0_2
> 0 <= x_0_3
> 0 <= x_0_4
> 0 <= x_0_5
> 0 <= x_0_6
> 0 <= x_0_7
> 0 <= x_0_8
> 0 <= x_0_9
> Generals
> x_0_0
> x_0_1
> x_0_10
> x_0_11
> x_0_12
> x_0_13
> x_0_14
> x_0_15
> x_0_16
> x_0_17
> x_0_18
> x_0_19
> x_0_2
> x_0_3
> x_0_4
> x_0_5
> x_0_6
> x_0_7
> x_0_8
> x_0_9
> End

I'm using pulp's default solver and the result I get is `x_0_0 = 1` and the rest of the variables equal to zero, with an objective function of 2594.0642408.

As far as I can tell the solution `x_0_1 = 1` and the rest of the variables equal to zero, is a better solution that satisfies all constraints, which would have objective function of 474.183785953.

**Comment by pchtsp** [comment] 2019-10-30 17:43
Hello,

thanks for the issue. Some questions to better understand your issue.

1. so you have a reproducible python code?
2. this seems a problem for CBC (the default solver), have you tried contacting their project? (https://github.com/coin-or/Cbc)
3. Do you actually need all those decimals? Sometimes solvers get crazy with excessive precision without being properly configured. Could you try scaling to get all integer coefficients?
4. Did you put a time limit on the solving? Did the solver say it was the optimal solution?

**Comment by joaomanke** [comment] 2019-11-01 11:05
Hello @pchtsp,

The original problem had decimals in the coefficients as well, I rounded them as a way to simplify, rounding some of the constraints values as well seems to do it.

I have that precision because these values are calculated from input data of my project, ideally I would want to not round/scale them (but I will if necessary), you said that the solvers get crazy without proper configuration, how would one do such configuration?

To answer your questions directly?

1. I do however the data is sensible so I can't really share with you :( , however the basic gist of it is just to create a problem, do a problem.solve().
2. I haven't but I will try raising an issue there.
3. See above.
4. I tried both with and without a time limit, both times with the same answer and Optimal Status.

**Comment by pchtsp** [comment] 2019-11-01 15:31
Hey!

The rounding question is important. So do you actually need all those decimals and are you sure more decimals give you more precision in this case? See https://en.wikipedia.org/wiki/Significant_figures.

If there is no impact between using 3 decimals ir 8, you can use 2 or 3 decimals and I believe you will have the expected behavior while keeping some level of precision. 

If, in the other hand, you're sure that you absolutely need all those numbers you'll have to write to the guys at cbc for them to tell you how you can modify your program (rescale it) or how to configure the solver to use more precision.

**Comment by pchtsp** [comment] 2020-07-07 07:11
since the rounding solve the issue I will close this one. If you happen to have other problems, do open a new issue.

**Closed by pchtsp** 2020-07-07 07:11 UTC
