### ISSUE TITLE
NoneType Variables

### ISSUE THREAD

**Issue by frogeyedpeas** [coin-or/pulp#110] opened 2016-08-10 18:15 UTC
Was using PuLP as a subroutine in a project in python 3.5.2, I noticed that for some LP's pulp was responding with variables that are "NoneType" claiming it had found an optimal solution. It appears that this occurs for certain unbounded LP's (with bounded variables). 

As an example: Here we specified the system x >=0, and tried to maximize x, ending up with a solution of x=1, y=None, which doesn't make any sense. See terminal output below:

> > > from pulp import *
> > > x = LpVariable('x',0,1)
> > > y = LpVariable('y',0,1)
> > > prob = LpProblem('Problem',LpMaximize)
> > > prob += -x<=0
> > > prob+=x
> > > status = prob.solve()
> > > print status
> > >   File "<stdin>", line 1
> > >     print status
> > >                ^
> > > SyntaxError: Missing parentheses in call to 'print'
> > > print(status)
> > > 1
> > > print(value(x))
> > > 1.0
> > > print(value(y))
> > > None

What I did to fix it:
Attempted to revert to older version of PuLP in python 2.7, same issues, attempted to re-install with pip, same issues.

**Comment by julianmukaj** [comment] 2020-02-18 14:45
Bump because I see the same issues

**Comment by pchtsp** [comment] 2020-02-18 19:50
Here the y variable was never filled because is not even part of the problem. There are no constraints that make reference to this variable. The default value of a newly created variable is none.

I don't see anything weird here. Do you have any recent reproducible example?

**Comment by julianmukaj** [comment] 2020-02-19 10:51
I can't share the full code but essentially we have 100 continuous variables, upper bound 0.2 lower 0.0. And we have a constraint that is:

prob += lpSum( math.ceil( value(vars[i]) ) for i in range(len(vars)) ) >= 50, "Minimum")

This gives us None types for the vars when doing math.ceil

**Comment by pchtsp** [comment] 2020-02-19 14:40
Hello again.

Thanks for the example.
I see at least two problems with the constraint you shared.

1. using `math.ceil` on pulp variables within a pulp constraint.
2. using the pulp function `value` inside a pulp constraint.

`pulp` only uses linear relationships between variables, so using `math.ceil` is not possible inside a constraint.

The reason why you get a `None` value is because pulp is probably ignoring this constraint. And so the variables are probably not being used in the model, resulting in the value `None`.

You would have something like the following, possibly:

    vars = LpVariable.dicts(name="vars", indexs=SOME_LIST, lowBound=0, upBound=SOME_PARAMETER, cat=LpInteger)
    prob += lpSum(vars[i] for i in range(len(vars)) ) >= 50, "Minimum")

It appears you want to model integer variables. For that you need to cofigure the variables as integer. And / or edit your formulation to take this into account. In any case, you may want to take a look at mathematical modelling resources so you can better understand what you can do with constraints and variables.

take care!

Franco

**Comment by pchtsp** [comment] 2020-02-20 17:55
I'm going to close this issue since both comments were not rally issues. Feel free to open a new issue if you feel otherwise!

**Closed by pchtsp** 2020-02-20 17:55 UTC
